spring.application.name=partion

server.port=8080

spring.profiles.active=local

mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

spring.ai.openai.chat.model=gpt-5-mini
spring.ai.openai.chat.temperature=0.3